# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ankush's Blog
#email: firstnamelastname(at)gmail(dot)com
description: > # this means to ignore newlines until "baseurl:"
  Thoughts. Musings. Inspirations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: ankushbhalotia
facebook_username: ankush.bhalotia
github_username:  ankushb92
linkedin_username: ankush-bhalotia
# Build settings
markdown: kramdown
